default['version']=0.1.0
default[jenkins][package]=java-1.8.0-openjdk-devel.x86_64
default[jenkins][repo]=https://pkg.jenkins.io/redhat-stable/jenkins.repo
default[jenkins][key]=https://pkg.jenkins.io/redhat-stable/jenkins.io.key
default['user']='jenkins'
default['group']='jenkins'
default['mode']=0755
default['port']=8080
end
